refactored snippet scripts

diff --git a/bin/add_snippet b/bin/add_snippet
--- a/bin/add_snippet
+++ b/bin/add_snippet
@@ -1,16 +1,34 @@
 #!/bin/bash
 
-SNIPPET_NAME=$1
-SNIPPET_SOURCE=$2
-touch temp
-flatten_snippet.py $SNIPPET_SOURCE | tr -d "'" > temp #create one-line version with literal newlines and tabs
-perl -i -pe 's/\\n/\\\\n/g' temp #replace \n with \\n
-perl -i -pe 's/\\t/\\\\t/g' temp #replace \t with \\t
-SNIPPET="${SNIPPET_NAME}=$(cat temp)"
-rm -f temp
-echo "Created $SNIPPET"
+if [ "$#" -ne 2 ]; then
+  echo "Usage: $0 <snippet-name> <snippet-source-file>"
+  exit 1
+fi
+
+snippet_name="$1"
+snippet_source="$2"
+snippet_lang="[C++]"
+conf_file="/usr/share/geany/snippets.conf"
+
+if [ ! -f "$snippet_source" ]; then
+  echo "Snippet source file not found!"
+  exit 1
+fi
+
+if [ ! -f "$conf_file" ]; then
+  echo "Geany snippet configuration file '$conf_file' not found!"
+  exit 1
+fi
+
+one_line_snippet=$(sed ':a;N;$!ba;s/\n/\\\\n/g' "$snippet_source" | sed 's/\t/\\\\t/g')
+one_line_snippet="${snippet_name}=${one_line_snippet}"
 
 sudo sed -i "
 /\[C++\]/ a\
-$SNIPPET
-" /usr/share/geany/snippets.conf
+$one_line_snippet
+" $conf_file
+
+echo "Appended the snippet under the language '$snippet_lang' in '$conf_file'."
+exit 1
+
+
